# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-dynamodb
  description: Terraform module that implements AWS DynamoDB with support for AutoScaling
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-modules, autoscaling, aws, dynamodb, dynamodb-table, dynamodb-database, hcl2

